from tkinter import *
root = Tk()
root.geometry("655x333")
def getData():
    fileptr = open("file1.txt", "a")
    name=firstname.get()
    fileptr.write(f"firstname:{name}\n")

    # closing the opened file
    fileptr.close()
def getval(event):
    print("hello tkinter")
    getData()
root.title("StudentDetails")
l1=Label(root,text="First Name ")
l2=Label(root,text="Last Name ")
l3=Label(root,text="Branch ")
l4=Label(root,text="Year ")
firstname=StringVar()
lastname=StringVar()
branch=StringVar()
year=StringVar()
f1=Entry(root,textvariable=firstname)
f2=Entry(root,textvariable=lastname)
f3=Entry(root,textvariable=branch)
f4=Entry(root,textvariable=year)
l1.grid(row=0,column=0)
l2.grid(row=0,column=2)
l3.grid(row=1,column=0)
l4.grid(row=1,column=2)
f1.grid(row=0,column=1)
f2.grid(row=0,column=3)
f3.grid(row=1,column=1)
f4.grid(row=1,column=3)
widget=Button(root,text="Submit",command=getData)
widget.grid()
widget.bind('<Double-1>',quit)
root.bind('<Return>',getval)
root.mainloop()
